# Site settings
title: 自我对话
email: chazho10@163.com
description: 我是写代码的
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
twitter:  kobras8
weibo: kobras
github: kobras8
codepen:  kobras
dribbble: kobras


# Comment
disqus_shortname: kobras8


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
